### ISSUE TITLE
Elasticsearch: Conceptos elementales y caso de estudio

### ISSUE THREAD

**Issue by domix** [perujug/propuestas-meetup#4]
La idea es introducir los conceptos de Elasticsearch, cuando y porque es bueno usarlo y mostrar un caso de estudio de la implementación de un cluster masivo en el sector bancario en México.

Referencias:
http://www.slideshare.net/domingo.suarez/elasticsearch-jvmmx-meetup-april-2016
http://www.slideshare.net/domingo.suarez/sgnext-elasticsearch

**Comment by eddumelendez** [comment]
Gracias por la charla @domix 👍
