### ISSUE TITLE
Moviendo datos con Akka Streams 

### ISSUE THREAD

**Issue by jeqo** [perujug/propuestas-meetup#8]
Finalmente he recogido experiencia implementando integraciones utilizando el set de herramientas de Akka. A diferencia de frameworks que definen la forma de trabajo en la implementacion de aplicaciones, librerias con Akka, ofrecen herramientas que pueden agregarse a tu aplicacion segun las necesidades. 

En esta presentacion revisaremos el set de herramientas que ofrece Akka, enfocandonos en Akka Streams como libreria para implementar integracion de datos. Tambien revisaremos Alpakka, que es el proyecto que incluye integraciones con distintos sistemas para permitir la adopcion de Akka Streams.

Brevemente, otras herramientas como Akka Actors y Akka HTTP seran descritas, pero cada una require de su propia charla.

Si hay interes por esta charla puedo agregar mayores detalles.

**Comment by joedayz** [comment]
Jorge, ahora Eddu está por USA y no regresa en 2 semanas. Si deseas te apoyo para hacerla en linea e invitar al  grupo. Alguna fecha disponible que tengas?

**Comment by jeqo** [comment]
No hay apuro :) coordinemos con calma para finales de Octubre, inicios de Noviembre.

**Comment by Miuler** [comment]
Que fe de esta iniciativa? me parece interesante.

**Comment by jeqo** [comment]
No he estado utilizando Akka Streams ultimamente, y no creo que tenga tiempo para retomarlo para una presentacion.  Pero queda abierto por si alguien mas la quiere llevar a cabo, si hay interes en la comunidad.

Estaba pensando en hacer una entrega sobre Kafka Streams. Voy a crear otro issue para esa :)
